In [2]:
#!pip3 install lightfm

  Created wheel for lightfm: filename=lightfm-1.16-cp38-cp38-win_amd64.whl size=423196 sha256=0f03a6996b3d86ed8c196e10e322c359a6d3f6454b971e360bcc7c742a20ec50
  Stored in directory: c:\users\user x\appdata\local\pip\cache\wheels\ec\bb\51\9c487d021c1373b691d13cadca0b65b6852627b1f3f43550fa
Successfully built lightfm


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Для работы с матрицами
from scipy.sparse import csr_matrix, coo_matrix

# Матричная факторизация
from implicit.als import AlternatingLeastSquares
from implicit.nearest_neighbours import bm25_weight, tfidf_weight

from lightfm import LightFM
from lightfm.evaluation import precision_at_k, recall_at_k

# Функции из 1-ого вебинара
import os, sys

module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)
    
# from src.metrics import precision_at_k, recall_at_k
from utils import prefilter_items

C:\ProgramData\Anaconda3\lib\site-packages\lightfm\_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(


In [2]:
data = pd.read_csv('retail_train.csv')

item_features = pd.read_csv('product.csv')
user_features = pd.read_csv('hh_demographic.csv')

# column processing
item_features.columns = [col.lower() for col in item_features.columns]
user_features.columns = [col.lower() for col in user_features.columns]

item_features.rename(columns={'product_id': 'item_id'}, inplace=True)
user_features.rename(columns={'household_key': 'user_id'}, inplace=True)

# train test split
test_size_weeks = 3

data_train = data[data['week_no'] < data['week_no'].max() - test_size_weeks]
data_test = data[data['week_no'] >= data['week_no'].max() - test_size_weeks]

data_train.head(2)

user_id    basket_id  day  item_id  quantity  sales_value  store_id  \
0     2375  26984851472    1  1004906         1         1.39       364   
1     2375  26984851472    1  1033142         1         0.82       364   

   retail_disc  trans_time  week_no  coupon_disc  coupon_match_disc  
0         -0.6        1631        1          0.0                0.0  
1          0.0        1631        1          0.0                0.0

In [3]:
item_features.head(2)

item_id  manufacturer    department     brand            commodity_desc  \
0    25671             2       GROCERY  National                  FRZN ICE   
1    26081             2  MISC. TRANS.  National  NO COMMODITY DESCRIPTION   

            sub_commodity_desc curr_size_of_product  
0          ICE - CRUSHED/CUBED                22 LB  
1  NO SUBCOMMODITY DESCRIPTION

In [4]:
user_features.head(2)

age_desc marital_status_code income_desc homeowner_desc      hh_comp_desc  \
0      65+                   A      35-49K      Homeowner  2 Adults No Kids   
1    45-54                   A      50-74K      Homeowner  2 Adults No Kids   

  household_size_desc kid_category_desc  user_id  
0                   2      None/Unknown        1  
1                   2      None/Unknown        7

In [5]:
user_features['age_desc'].unique()

array(['65+', '45-54', '25-34', '35-44', '19-24', '55-64'], dtype=object)

In [6]:
user_features['marital_status_code'].unique()

array(['A', 'U', 'B'], dtype=object)

In [7]:
user_features['household_size_desc'].unique()

array(['2', '3', '4', '1', '5+'], dtype=object)

## 1. Filter items

In [9]:
data_train.head()

user_id    basket_id  day  item_id  quantity  sales_value  store_id  \
0     2375  26984851472    1  1004906         1         1.39       364   
1     2375  26984851472    1  1033142         1         0.82       364   
2     2375  26984851472    1  1036325         1         0.99       364   
3     2375  26984851472    1  1082185         1         1.21       364   
4     2375  26984851472    1  8160430         1         1.50       364   

   retail_disc  trans_time  week_no  coupon_disc  coupon_match_disc  
0        -0.60        1631        1          0.0                0.0  
1         0.00        1631        1          0.0                0.0  
2        -0.30        1631        1          0.0                0.0  
3         0.00        1631        1          0.0                0.0  
4        -0.39        1631        1          0.0                0.0

In [12]:
n_items_before = data_train['item_id'].nunique()

data_train_filtered = prefilter_items(data_train, take_n_popular=5000, item_features=item_features)

n_items_after = data_train_filtered['item_id'].nunique()
print('Decreased # items from {} to {}'.format(n_items_before, n_items_after))

Decreased # items from 86865 to 86865


# 2. Prepare data set

## 2.1 Prepare csr train matrix

In [13]:
user_item_matrix = pd.pivot_table(data_train, 
                                  index='user_id', columns='item_id', 
                                  values='quantity', # Можно пробоват ьдругие варианты
                                  aggfunc='count', 
                                  fill_value=0
                                 )

user_item_matrix = user_item_matrix.astype(float) # необходимый тип матрицы для implicit

# переведем в формат sparse matrix
sparse_user_item = csr_matrix(user_item_matrix).tocsr()

user_item_matrix.head(2)

item_id  25671     26081     26093     26190     26355     26426     26540     \
user_id                                                                         
1             0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2             0.0       0.0       0.0       0.0       0.0       0.0       0.0   

item_id  26601     26636     26691     ...  17328742  17329473  17329749  \
user_id                                ...                                 
1             0.0       0.0       0.0  ...       0.0       0.0       0.0   
2             0.0       0.0       0.0  ...       0.0       0.0       0.0   

item_id  17330255  17330511  17381856  17382205  17383227  17827644  17829232  
user_id                                                                        
1             0.0       0.0       0.0       0.0       0.0       0.0       0.0  
2             0.0       0.0       0.0       0.0       0.0       0.0       0.0  

[2 rows x 86865 columns]

## 2.2 Prepare CSR test matrix

In [14]:
data_test = data_test[data_test['item_id'].isin(data_train['item_id'].unique())]

test_user_item_matrix = pd.pivot_table(data_test, 
                                  index='user_id', columns='item_id', 
                                  values='quantity', # Можно пробоват ьдругие варианты
                                  aggfunc='count', 
                                  fill_value=0
                                 )

test_user_item_matrix = test_user_item_matrix.astype(float) # необходимый тип матрицы для implicit

In [15]:
userids = user_item_matrix.index.values
itemids = user_item_matrix.columns.values

matrix_userids = np.arange(len(userids))
matrix_itemids = np.arange(len(itemids))

id_to_itemid = dict(zip(matrix_itemids, itemids))
id_to_userid = dict(zip(matrix_userids, userids))

itemid_to_id = dict(zip(itemids, matrix_itemids))
userid_to_id = dict(zip(userids, matrix_userids))

## 3. Prepare user and item features

In [16]:
user_feat = pd.DataFrame(user_item_matrix.index)
user_feat = user_feat.merge(user_features, on='user_id', how='left')
user_feat.set_index('user_id', inplace=True)
user_feat.head(2)

age_desc marital_status_code income_desc homeowner_desc  \
user_id                                                           
1            65+                   A      35-49K      Homeowner   
2            NaN                 NaN         NaN            NaN   

             hh_comp_desc household_size_desc kid_category_desc  
user_id                                                          
1        2 Adults No Kids                   2      None/Unknown  
2                     NaN                 NaN               NaN

In [17]:
user_feat.shape

(2499, 7)

In [18]:
item_feat = pd.DataFrame(user_item_matrix.columns)
item_feat = item_feat.merge(item_features, on='item_id', how='left')
item_feat.set_index('item_id', inplace=True)

item_feat.head(2)

manufacturer    department     brand            commodity_desc  \
item_id                                                                   
25671               2       GROCERY  National                  FRZN ICE   
26081               2  MISC. TRANS.  National  NO COMMODITY DESCRIPTION   

                  sub_commodity_desc curr_size_of_product  
item_id                                                    
25671            ICE - CRUSHED/CUBED                22 LB  
26081    NO SUBCOMMODITY DESCRIPTION

In [19]:
item_feat.shape

(86865, 6)

## Encoding features

In [20]:
user_feat_lightfm = pd.get_dummies(user_feat, columns=user_feat.columns.tolist())
item_feat_lightfm = pd.get_dummies(item_feat, columns=item_feat.columns.tolist())

In [21]:
user_feat_lightfm.head(2)

age_desc_19-24  age_desc_25-34  age_desc_35-44  age_desc_45-54  \
user_id                                                                   
1                     0               0               0               0   
2                     0               0               0               0   

         age_desc_55-64  age_desc_65+  marital_status_code_A  \
user_id                                                        
1                     0             1                      1   
2                     0             0                      0   

         marital_status_code_B  marital_status_code_U  income_desc_100-124K  \
user_id                                                                       
1                            0                      0                     0   
2                            0                      0                     0   

         ...  hh_comp_desc_Unknown  household_size_desc_1  \
user_id  ...                                                
1        ...                     0                      0   
2        ...                     0                      0   

         household_size_desc_2  household_size_desc_3  household_size_desc_4  \
user_id                                                                        
1                            1                      0                      0   
2                            0                      0                      0   

         household_size_desc_5+  kid_category_desc_1  kid_category_desc_2  \
user_id                                                                     
1                             0                    0                    0   
2                             0                    0                    0   

         kid_category_desc_3+  kid_category_desc_None/Unknown  
user_id                                                        
1                           0                               1  
2                           0                               0  

[2 rows x 41 columns]

In [22]:
item_feat_lightfm.head(2)

manufacturer_1  manufacturer_2  manufacturer_3  manufacturer_4  \
item_id                                                                   
25671                 0               1               0               0   
26081                 0               1               0               0   

         manufacturer_5  manufacturer_6  manufacturer_8  manufacturer_9  \
item_id                                                                   
25671                 0               0               0               0   
26081                 0               0               0               0   

         manufacturer_10  manufacturer_11  ...  curr_size_of_product_TWIN  \
item_id                                    ...                              
25671                  0                0  ...                          0   
26081                  0                0  ...                          0   

         curr_size_of_product_TWIN PACK  curr_size_of_product_UNDER 15LB  \
item_id                                                                    
25671                                 0                                0   
26081                                 0                                0   

         curr_size_of_product_X-LARGE  curr_size_of_product_X-LG  \
item_id                                                            
25671                               0                          0   
26081                               0                          0   

         curr_size_of_product_XL  curr_size_of_product_XL/3PK  \
item_id                                                         
25671                          0                            0   
26081                          0                            0   

         curr_size_of_product_XL/6PK  curr_size_of_product_XLG  \
item_id                                                          
25671                              0                         0   
26081                              0                         0   

         curr_size_of_product_XLRG  
item_id                             
25671                            0  
26081                            0  

[2 rows x 13109 columns]

## Init model

In [23]:
model = LightFM(no_components=40,
#                 loss='bpr',
                loss='warp',
                learning_rate=0.05, 
                item_alpha=0.1,
                user_alpha=0.1, 
                random_state=42)

## Train

In [24]:
model.fit((sparse_user_item > 0) * 1,  # user-item matrix из 0 и 1
          sample_weight=coo_matrix(user_item_matrix),
          user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
          item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
          epochs=15, 
          num_threads=4,
          verbose=False) 

# Evaluation

In [25]:
user_emb = model.get_user_representations(features=csr_matrix(user_feat_lightfm.values).tocsr())

In [26]:
user_emb[0]  # biases

array([-90.14359,   0.     ,   0.     , ..., -93.94484, -64.3351 ,
         0.     ], dtype=float32)

In [27]:
user_emb[1]  # embeddings

array([[-8.0002316e-10, -1.9263866e-09, -1.7843060e-09, ...,
         4.3063366e-09, -2.2615159e-09, -4.3190740e-09],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [-3.8009595e-10, -2.3463458e-09,  1.9403679e-10, ...,
         6.3746786e-09, -1.4716695e-09, -5.2020557e-09],
       [-2.2383055e-09, -8.2167961e-10, -1.5713173e-09, ...,
         6.1825807e-09, -4.2799848e-09, -6.7039498e-09],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [28]:
user_emb[0].shape

(2499,)

In [29]:
user_emb[1]  # embeddings

array([[-8.0002316e-10, -1.9263866e-09, -1.7843060e-09, ...,
         4.3063366e-09, -2.2615159e-09, -4.3190740e-09],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [-3.8009595e-10, -2.3463458e-09,  1.9403679e-10, ...,
         6.3746786e-09, -1.4716695e-09, -5.2020557e-09],
       [-2.2383055e-09, -8.2167961e-10, -1.5713173e-09, ...,
         6.1825807e-09, -4.2799848e-09, -6.7039498e-09],
       [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [30]:
user_emb[1].shape

(2499, 40)

In [31]:
item_emb = model.get_item_representations(features=csr_matrix(item_feat_lightfm.values).tocsr())

In [32]:
item_emb[0].shape

(86865,)

In [33]:
item_emb[1].shape

(86865, 40)

# Train precision

In [35]:
train_precision = precision_at_k(model, sparse_user_item, 
                                 user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
                                 item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
                                 k=5).mean()

train_precision

0.051700678

In [36]:
test_item_ids = np.array([1, 2, 3, 200, 1200])

predictions = model.predict(user_ids=0,
                            item_ids=test_item_ids,
                            user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
                            item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
                            num_threads=4)

In [37]:
predictions

array([-90.44566, -89.89013, -89.91607, -90.23582, -89.87319],
      dtype=float32)

# Test precision

In [38]:
test_precision = precision_at_k(model, csr_matrix(test_user_item_matrix).tocsr(), 
                                 user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
                                 item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
                                 k=5).mean()

test_precision

0.0022537974

# Домашнее задание

In [66]:
hyperparameters = model.get_params()
hyperparameters

{'loss': 'warp',
 'learning_schedule': 'adagrad',
 'no_components': 40,
 'learning_rate': 0.05,
 'k': 5,
 'n': 10,
 'rho': 0.95,
 'epsilon': 1e-06,
 'max_sampled': 10,
 'item_alpha': 0.1,
 'user_alpha': 0.1,
 'random_state': RandomState(MT19937) at 0x1C0CC3F4B40}

In [67]:
learning_rate = list(np.linspace(0, 1, 10))  
item_alpha = list(np.linspace(0, 1, 10))
user_alpha = list(np.linspace(0, 1, 10))    

In [ ]:
for i in learning_rate:
    for j in item_alpha:
        for k in user_alpha:
            model = LightFM(no_components=40, loss='warp', learning_rate=i, item_alpha=j, user_alpha=k, random_state=42)
            model.fit((sparse_user_item > 0) * 1,
                      sample_weight=coo_matrix(user_item_matrix),
                      user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
                      item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
                      epochs=15, 
                      num_threads=4,
                      verbose=False)
            test_precision = precision_at_k(model, csr_matrix(test_user_item_matrix).tocsr(), 
                                 user_features=csr_matrix(user_feat_lightfm.values).tocsr(),
                                 item_features=csr_matrix(item_feat_lightfm.values).tocsr(),
                                 k=5).mean()
            print(f'learning_rate = {i}, item_alpha = {j}, user_alpha = {k}, test_precision = {test_precision}')

learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.0, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.1111111111111111, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.2222222222222222, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.3333333333333333, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.4444444444444444, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.5555555555555556, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.6666666666666666, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.7777777777777777, test_precision = 0.0012738852528855205
learning_rate = 0.0, item_alpha = 0.0, user_alpha = 0.8888888888888888, test_precision = 0.0012738852528855205
learning_rate = 